async def department_list_handler(): ...


async def department_member_list_handler(): ...


async def add_department_handler(): ...


async def remove_department_handler(): ...


async def add_department_member_handler(): ...


async def remove_department_member_handler(): ...


async def add_department_minister_handler(): ...


async def remove_department_minister_handler(): ...
