"""sync department table

Revision ID: 1a9da5d83261
Revises: 
Create Date: 2025-11-27 20:55:39.540560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9da5d83261'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('code', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'departments', ['code'])
    op.alter_column('users', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'major',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'class_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'class_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'major',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'code')
    # ### end Alembic commands ###
