"""设置User.mc_name为nullable

Revision ID: 476fbcb0a384
Revises: 
Create Date: 2025-11-18 13:13:13.639410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476fbcb0a384'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mc_name',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mc_name',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
    # ### end Alembic commands ###
